# Generated by Django 5.2.13 on 2026-04-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
    ]
