# Generated by Django 5.2.13 on 2026-04-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0002_payout_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
